word_list = [
  'Abeceda', 
  'Miš',
  'Škola',
  'Oglas', 
  'Slušati', 
  'Frižider', 
  'Harmonika',
  'Šahovska ploča', 
  'Drvo', 
  'Flauta', 
  'Hrvatski jezik', 
  'Ponedjeljak', 
  'Utorak', 
  'Srijeda', 
  'Četvrtak', 
  'Subota',
  'Sunce',
  'Prestolonasljednik',
  'Nogomet',
  'Utakmica',
  'Krivolovac',
  'Marketing',
  'Zrakoplov',
  'Helikopter',
  'Šumski čistac',
  'Pelete',
  'Divlji zumbuli',
  'Kravica'
]